### PR TITLE
More complete FileIO support

### PR DESCRIPTION
**Pull request by staticfloat**
This provides more complete `FileIO` support by transparently passing kwargs through to the internal `wavread`/`wavwrite` functions.

### CODE REVIEW

**Comment by dancasimiro** [comment]
Thanks for the PR @staticfloat. Do you know why the tests are failing?

**Comment by staticfloat** [comment]
The tests are failing on `master` as well; it's because of array changes in `0.5`; there are a wider set of classes that inherit from `AbstractArray` and so your type annotations should be expecting an `AbstractArray`, not just an `Array`.

**Comment by dancasimiro** [comment]
I'm sorry, but I pushed a fix for the test failures before I noticed that you also fixed that problem in this pull request. Could you please rebase so that I can automatically merge this pull request?

Is this FileIO support sufficient that I can tag a release?

**Comment by staticfloat** [comment]
Rebase complete.  It looks like there was still one method that needed to be moved from `Array` to `AbstractArray`

Yes, I think the `FileIO` stuff is feature-complete enough to publish a new version.

**Pull request merged**
